### ISSUE TITLE
screenshot extraction

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/carmel-fe#15]
I've tried to divide this task in mostly equal halves..
Man, you've got a whole lot of components there. 😂 

I think you should be able to edit this post (as I'm able to edit yours). So you should also be able to check the boxes.

### Daniel

- [x] Editors
  - [x] Autocomplete
  - [x] Colorpicker
  - [x] Combobox
  - [x] DatePicker
  - [x] DateTimePicker
  - [x] DropDownList
  - [x] Editor
  - [x] MaskedTextBox
  - [x] MultiSelect
  - [x] NumericTextBox
  - [x] RangeSlider
  - [x] Slider
  - [x] TimePicker
  - [x] Upload
  - [x] Validator
  - [x] Switch

---

- [x] Layout
  - [x] Dialog
  - [x] Notification
  - [x] Responsive Panel
  - [x] Splitter
  - [x] Tooltip
  - [x] Window

---

- [x] Navigation
  - [x] Button
  - [x] ButtonGroup
  - [x] Menu
  - [x] PanelBar
  - [x] TabBar
  - [x] ToolBar
  - [x] TreeView

---

- [x] Gauges
  - [x] Linear
  - [x] Radial

---

- [x] Scheduling
  - [x] Calendar
  - [x] Gantt
  - [x] Scheduler

---

### Nik

- [x] Charts
  - [x] Area
  - [x] Bar
  - [x] Box Plot
  - [x] Bubble
  - [x] Bullet
  - [x] Donut
  - [x] Funnel
  - [x] Line
  - [x] Pie
  - [x] Polar
  - [x] Radar
  - [x] Range Bar
  - [x] Scatter
  - [x] Sparklines
  - [x] Stock
  - [x] TreeMap
  - [x] Waterfall

---

- [x] Data Management
  - [x] Grid
  - [x] Spreadsheet
  - [x] ListView
  - [x] PivotGrid
  - [x] TreeList
  - [x] ScrollView

---

- [x] BarCodes
  - [x] Barcode
  - [x] QR Code

---

- [x] Interactivity & UX
  - [x] Drag&Drop
  - [x] ProgressBar
  - [x] Sortable

---

- [x] Diagrams & Maps
  - [x] Diagram
  - [x] Map

---

**Comment by Thanood** [comment]
My approach so far:

- open paint.net (or any other good image editor) (https://www.getpaint.net)
- open KendoUI bridge (https://aurelia-ui-toolkits.github.io/demo-kendo/#/catalog-index)
- open the sample
- press `Alt+print`
- paste into the image editor
- crop the image so that the relevant result of the sample is visible
- open KendoUI bridge tab from step 3
- right click on "Run", copy link address
- open image editor and save
- paste the gist url from KendoUI bridge and remove everything but the id
- add `.png` to the end (if the image editor doesn't do that for you)
- commit the single file immediately to git, with the sample name in commit message (easier to find later)

**Comment by Thanood** [comment]
Is this really an autocomplete sample?
https://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/autocomplete-with.bind

Looks like date-picker and fetching the gist files does not seem to work.

**Comment by adriatic** [comment]
> Is this really an autocomplete sample?

Apparently not - I will create the issue for Jeroen!

https://github.com/aurelia-ui-toolkits/demo-kendo/issues/11

**Comment by adriatic** [comment]
This is the 1016 x 978 window taken on my monitor - we do have a scaling issue here - how does this compare with your screenshots?

![image](https://cloud.githubusercontent.com/assets/2712405/25283773/e05e5a66-2682-11e7-9d67-d7598b66c44f.png)

**Comment by adriatic** [comment]
My snagit seems to have taken over some of the shortcuts, so `alt+print` does not do anything. Let's try this way:

The image below is `a346680615fca14ec68b94b0c3a47e01` (Colorpicker: basic use) taken with snagit by selecting just the frame drawn by `https://gist.run/?id=a346680615fca14ec68b94b0c3a47e01`

<img  alt="color-picker-basic use" src="https://cloud.githubusercontent.com/assets/2712405/25286373/84b07678-268b-11e7-8ce9-45e092b5cec4.png">


How does this compare (viewed on your own computer) with the same item that you took

To avoid sideeffects from GitHub, I am also attaching this same .png as an attachment to the email sent to your aureliatools.com address.

**Comment by Thanood** [comment]
> How does this compare (viewed on your own computer) with the same item that you took.

It's a lot bigger (930x928 vs 600x600). 😕 
And I was wrong, the image has the correct size when zooming to 67% (I'm suspecting 2/3) of its original size.

So you're right, the windows subsystem does something "interesting" to the image. GitHub doesn't compensate anything btw, it has the same size (also the same as in the mail). The width is changed here to fit the container but clicking on the picture opens the original with original dimensions.

**Comment by Thanood** [comment]
For comparison: the image taken with `alt+print` on my computer..

![image](https://cloud.githubusercontent.com/assets/677826/25302612/0a58899e-2742-11e7-9945-3d8b633760fd.png)

**Comment by adriatic** [comment]
Just sent you the email with this same screenshot taken on my monitor and then scaled down 65% (ratio of 600 and 930)

<img  alt="color-picker-basic use-nik-scaled" src="https://cloud.githubusercontent.com/assets/2712405/25305247/d72c17a8-2745-11e7-88e2-e0c7f9732175.png">

(note that both images (**[yours](https://github.com/aurelia-ui-toolkits/carmel-fe/issues/15#issuecomment-296356073)** and mine above) render the same way on my monitor)

**Comment by Thanood** [comment]
604 x 603 looks good to me 👍

**Comment by adriatic** [comment]
OK, then consider your initial distribution of screenshot happily accepted.

**Comment by Thanood** [comment]
all done 😃

**Comment by adriatic** [comment]
Wonderful - thank you!
