### ISSUE TITLE
Issues deploying carmel-fe to GitHub pages

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/carmel-fe#18]
I added the new gulp task - **[deploy](https://github.com/aurelia-ui-toolkits/carmel-fe/blob/master/build/tasks/deploy.js)** as a slightly modified copy of the same-named code from **`demo-kendo`** (Kendo catalog application).

Note that I commented out **[the line](https://github.com/aurelia-ui-toolkits/carmel-fe/blob/master/build/tasks/deploy.js#L30)** that does the "push" to GitHub and replaced it with **[this](https://github.com/aurelia-ui-toolkits/carmel-fe/blob/master/build/tasks/deploy.js#L29)** which creates the **`test-dist`** folder, so I can run the site locally before publishing it.

This "local instance" fails (see below), so I am leaving this task to you, as there seem to be a problem with the "old tag editor" or something similar.

```
Failed to load resource: net::ERR_FILE_NOT_FOUND
jquery.caret.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
jquery.tag-editor.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
css Failed to load resource: net::ERR_FILE_NOT_FOUND
system.js:4 XMLHttpRequest cannot load file:///H:/work/aurelia-ui-toolkits/carmel-fe/test-dist/dist/aurelia.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
W @ system.js:4
(anonymous) @ system.js:4
e._execute @ bluebird.min.js:29
r._resolveFromExecutor @ bluebird.min.js:30
r @ bluebird.min.js:30
(anonymous) @ system.js:4
(anonymous) @ system.js:5
(anonymous) @ system.js:5
(anonymous) @ system.js:5
(anonymous) @ system.js:5
(anonymous) @ system.js:5
(anonymous) @ system.js:5
(anonymous) @ system.js:4
r @ bluebird.min.js:31
r._settlePromiseFromHandler @ bluebird.min.js:30
r._settlePromise @ bluebird.min.js:30
r._settlePromise0 @ bluebird.min.js:30
r._settlePromises @ bluebird.min.js:30
r._drainQueue @ bluebird.min.js:29
r._drainQueues @ bluebird.min.js:29
drainQueues @ bluebird.min.js:29
bluebird.min.js:29 Unhandled rejection (SystemJS) XHR error loading file:///H:/work/aurelia-ui-toolkits/carmel-fe/test-dist/dist/aurelia.js
	Error: XHR error loading file:///H:/work/aurelia-ui-toolkits/carmel-fe/test-dist/dist/aurelia.js
	    at r.e._execute (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:29:18668)
	    at r._resolveFromExecutor (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:12611)
	    at new r (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:4993)
	    at r (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:31:7722)
	    at r._settlePromiseFromHandler (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:13014)
	Error loading file:///H:/work/aurelia-ui-toolkits/carmel-fe/test-dist/dist/aurelia.js
	Error loading file:///H:/work/aurelia-ui-toolkits/carmel-fe/test-dist/jspm_packages/npm/aurelia-bootstrapper@1.0.1.js
D @ bluebird.min.js:29
k @ bluebird.min.js:29
E @ bluebird.min.js:29
e._notifyUnhandledRejection @ bluebird.min.js:29
r._drainQueue @ bluebird.min.js:29
r._drainQueues @ bluebird.min.js:29
drainQueues @ bluebird.min.js:29
```

**Comment by Thanood** [comment]
Strange.. I can't see that it's loaded anywhere. It's not even in `config.js` or `package.json`.
Is `jquery.tag-editor` in your `config.js`?

Where does the bundler get that from when it's not even there? 😕

**Comment by Thanood** [comment]
Ah, sorry. I forgot to remove the references from `index.html`..

I've fixed that now. Also, I added the bundles to `deploy` but the kendo bridge is still missing in bundles.
Can you add that in?
I'm also not sure about including the jquery package since kendo brings its own, right?

**Comment by adriatic** [comment]
> I added the bundles to deploy but the kendo bridge is still missing in bundles.
Can you add that in?

Not sure that I understand this - as there is no need to have the bridge in this app (we are just showing screenshots instead of running the actual samples). So, I did not do anything with regard to this request.

> I added the bundles ...

I never dealt with any bundling, so I compared [your definition of bundles section](https://github.com/aurelia-ui-toolkits/carmel-fe/blob/master/build/bundles.js) with the [bundles section for kendo-demo](https://github.com/aurelia-ui-toolkits/demo-kendo/blob/master/build/bundles.js) - and observed significant differences. Nevertheless, I enabled the [GitHub Pages settings](https://github.com/aurelia-ui-toolkits/carmel-fe/settings) and run `gulp deploy` task, which finished with no errors. However, trying to run the website at https://aurelia-ui-toolkits.github.io/carmel-fe/ I got 
```
 https://aurelia-ui-toolkits.github.io/carmel-fe/jspm_packages/npm/font-awesome@4.6.3/css/font-awesome.min.css 
(index):32 GET https://aurelia-ui-toolkits.github.io/carmel-fe/jspm_packages/system.js 
(index):32 GET https://aurelia-ui-toolkits.github.io/carmel-fe/jspm_packages/system.js 
config.js:1 Uncaught ReferenceError: System is not defined
    at config.js:1
(anonymous) @ config.js:1
(index):35 Uncaught ReferenceError: System is not defined
    at (index):35
```

Can you please verify my observed situation (I noted that you changed some stuff in the carmel-fe repo, but I did not try with these added changes as I am trying to get the auth stuff moving ahead)? It would be nice if you manage to get carmel-fe deployed to gh-pages 😏

**Comment by Thanood** [comment]
In principle it should be fixed now. All the files are present in the `gh-pages` branch.
But when I look at the network tab in Chrome, I'm seeing some files which cannot be loaded. *These files are definitely present* in the directory which they are loaded from.

For example, the following request fails: `https://aurelia-ui-toolkits.github.io/carmel-fe/jspm_packages/system.js`

But the file is [right there](https://github.com/aurelia-ui-toolkits/carmel-fe/tree/gh-pages/jspm_packages).

**Comment by adriatic** [comment]
This **is** the reason that "made me quit" on bundling yesterday, as I knew that missing `font-awesome` ought to be easy to address. I remember Jeroen sweating bullets when trying to get the gh-pages based demo-kendo to work. 

Several options:
1. Ask Jeroen (I do not want to do that myself)
2. Ask GitHub support
3. Start small and try to deploy Aurelia-Navigation skeleton first and then keep adding more code until it fails. 

I am happy to take on option 2 and 3, meaning that you leave Carmel-fe at this point until I come back here. Agreed?

**Comment by Thanood** [comment]
1. I've asked Jeroen on a previous issue I had with demo-materialize. He answered that the `gh-pages` build may not have completed and that I can trigger the build again when I push something to `gh-pages`. I did that several times but no avail.

2. Before any of us does that: Can you have a look at the `gh-pages` branch and confirm or "disprove" (not sure of the correct word) that `jspm_packages/system.js` is indeed there and at the correct path?

3. I can try and push something manually. Maybe just the missing files.

**Comment by adriatic** [comment]
I will do 2 right away and state my findings here: -->

I found this in deploy.js file:
```
    './dist/aurelia.js',
    './dist/app-build.js'
  ], { base: '.' })
<<<<<<< HEAD
     //.pipe(gulp.dest('./test-dist')) // for debugging
     .pipe(ghPages());
=======
     .pipe(gulp.dest('./test-dist')); // for debugging
    //.pipe(ghPages());
>>>>>>> 7d0207f5fd7c3e088fa494df9edecccb689e3288
});
```

Should I take it that you ran gulp watch with `.pipe(gulp.dest('./test-dist'));` active? If so, how did you test this app being in `test-dist` folder?

**Comment by Thanood** [comment]
I have switched the commented regions locally. I did not commit that on purpose to not deploy to `gh-pages` by accident. 😃 

Btw.: It works perfectly in `test-dist`.

**Comment by adriatic** [comment]
No seriously, I do not care about commits, but your testing. Perhaps I do not have the correct understanding of gh-pages, so let's quickly verify it:

If you run the `gulp deploy` with `.pipe(gulp.dest('./test-dist'));` enabled the folder that gets generated on your file system could be inspected for completeness - it cannot be run from the file system:
```
Failed to load resource: net::ERR_FILE_NOT_FOUND
system.js:4 XMLHttpRequest cannot load file:///H:/work/aurelia-ui-toolkits/carmel-fe/test-dist/dist/aurelia.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
W @ system.js:4
(anonymous) @ system.js:4
e._execute @ bluebird.min.js:29
r._resolveFromExecutor @ bluebird.min.js:30
r @ bluebird.min.js:30
(anonymous) @ system.js:4
(anonymous) @ system.js:5
(anonymous) @ system.js:5
(anonymous) @ system.js:5
(anonymous) @ system.js:5
(anonymous) @ system.js:5
(anonymous) @ system.js:5
(anonymous) @ system.js:4
r @ bluebird.min.js:31
r._settlePromiseFromHandler @ bluebird.min.js:30
r._settlePromise @ bluebird.min.js:30
r._settlePromise0 @ bluebird.min.js:30
r._settlePromises @ bluebird.min.js:30
r._drainQueue @ bluebird.min.js:29
r._drainQueues @ bluebird.min.js:29
drainQueues @ bluebird.min.js:29
bluebird.min.js:29 Unhandled rejection (SystemJS) XHR error loading file:///H:/work/aurelia-ui-toolkits/carmel-fe/test-dist/dist/aurelia.js
	Error: XHR error loading file:///H:/work/aurelia-ui-toolkits/carmel-fe/test-dist/dist/aurelia.js
	    at r.e._execute (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:29:18668)
	    at r._resolveFromExecutor (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:12611)
	    at new r (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:4993)
	    at r (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:31:7722)
	    at r._settlePromiseFromHandler (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:13014)
	Error loading file:///H:/work/aurelia-ui-toolkits/carmel-fe/test-dist/dist/aurelia.js
	Error loading file:///H:/work/aurelia-ui-toolkits/carmel-fe/test-dist/jspm_packages/npm/aurelia-bootstrapper@1.0.1.js
D @ bluebird.min.js:29
k @ bluebird.min.js:29
E @ bluebird.min.js:29
e._notifyUnhandledRejection @ bluebird.min.js:29
r._drainQueue @ bluebird.min.js:29
r._drainQueues @ bluebird.min.js:29
drainQueues @ bluebird.min.js:29
```

Of on the other hand , you enable the `.pipe(ghPages());` line then the app should be deployed as `
 Your site is published at https://aurelia-ui-toolkits.github.io/carmel-fe/` which when invoked renders this

![image](https://cloud.githubusercontent.com/assets/2712405/25626675/4aefc848-2f2e-11e7-8254-5ae67f56871e.png)

So, there is the issue related to gh-pages based deployment not finding `fonts-awesome` and `system.js`. the first item ought to be the consequence of not being defined somewhere and the other is a bigger mystery.

I am open to debug this - but this **is your app** 😄 - so I will do it only if it will help with your schedule. Let me know please.

**Comment by Thanood** [comment]
I'm not sure if we're on the same track right now regarding this conversation. :smiley:
I'd like to clear that up but I'm on my phone right now so this has to wait. 

Please check exactly why it's not runnable from the file system. It's not related to my setup. BTW I've used a global installation of http-server (npm) to verify that it works. 

I've picked system.js as an example. I did not mean that it's the only file which is not found but present. :smiley:

I'd will try it again later with some manual commits to gh-pages.

**Comment by adriatic** [comment]
> I'm not sure if we're on the same track right now regarding this conversation. 😃

We clearly are not - because I am a fool and you should not be on the same track with fools. Your explanation `BTW I've used a global installation of http-server (npm) to verify that it works.` woke me up (I was dealing with incredibly persistent bugs in my online banking system, that their support stuff fails to recognize and as a consequence I am paying hundreds of dollars in late fees for no reason whatsoever. Running this "human debugging thread" for hours in parallel with our discussion clearly took too many "CPU" cycles away from me.
