### ISSUE TITLE
git problem with .publish submodule

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/carmel-fe#21]
@adriatic What is this submodule?

![image](https://cloud.githubusercontent.com/assets/677826/25751448/55ebf666-31b5-11e7-9b42-ce6bcbcaaeed.png)

I'm having problems with it (I think it's temporary during gh-pages task).
It's checked into git as a directory and git thinks it's a file while it's really a directory and it appears as a submodule. I cannot push that to master.

Can I delete it from the git index and ignore it or do you use it for anything?
If so, please tell me what it is. 😃

**Comment by adriatic** [comment]
I am in the middle of debugging the correct app structure I want to use with Auth0, so give an hour to have a look at this. As I remember, I had no use for `gh-pages` task in "my" version of bundle + deploy, nor do I see .publish folder - so I suspect that we are still using different solution for this task.

**Comment by Thanood** [comment]
Yep, sorry.. Apparently I'm the one to blame.
It first occured in one of my commits.
